### ISSUE TITLE
What is the purpose of CSS classes .one .two .three?

### ISSUE THREAD

**Issue by fsmanuel** [twokul/ember-lazy-image#14]
https://github.com/twokul/ember-lazy-image/blob/master/vendor/lazy-image/lazy-image.css#L35-L57

That hit me hard. Now all my grid classes are fading in and out ;)

**Comment by twokul** [comment]
@fsmanuel those are for animating loading dots in "Loading..."

**Comment by twokul** [comment]
I don't they're used so I might as well just delete them
