### ISSUE TITLE
What about using ember-in-viewport

### ISSUE THREAD

**Issue by fsmanuel** [twokul/ember-lazy-image#21]
* https://github.com/dockyard/ember-in-viewport

Beside the fact that it uses es6 extensively it would give us performance by unbinding the event listeners and more options on `viewportTolerance`/`threshold`.

I could rename `enteredViewport ` to `viewportEntered` and replace the mixins.

@poteto what do you think? is ember-in-viewport ready or should we wait for `1.0.0`

**Comment by poteto** [comment]
Heya, yeah it is ready. I improved on the existing mixin that this addon uses, and importing it in should be a performance boost. I haven't bumped it to 1.0.0 because there's a few more things I'd like to add, but as it is it's a good drop in replacement for the current mixin.

**Comment by fsmanuel** [comment]
@poteto sounds good.

@twokul what do you think? I would update the readme as well to surface ember-in-viewport options.

**Comment by twokul** [comment]
@fsmanuel I'm :+1: :+1: :+1: on it. I had to add [`threshold`](https://github.com/twokul/ember-lazy-image/blob/master/addon/mixins/in-viewport.js#L15) option for lazy image so we should probably take that into account. @poteto thanks for the addon!

**Comment by fsmanuel** [comment]
@twokul should we deprecate `threshold` or use it as a shorthand? i'm more in favor of deprecation because `viewportTolerance` is much more precise.

**Comment by twokul** [comment]
@fsmanuel seems good.
