### ISSUE TITLE
Hocks vs. viewportEntered

### ISSUE THREAD

**Issue by fsmanuel** [twokul/ember-lazy-image#26]
@poteto What is the recommended way to catch the viewportEntered changes. We are using both and that breaks the addon:
https://github.com/twokul/ember-lazy-image/blob/master/addon/components/lazy-image.js#L36-L47

You first trigger the event and than set `viewportEntered`:
https://github.com/dockyard/ember-in-viewport/blob/76cc70431d025cff28fd2f775490e8fc36cc5535/addon/mixins/in-viewport.js#L145-L147

In our case the set seems to be too late and the image will never be visible.

As I understand it we no longer need to check `if (viewportEntered && lazyUrl === "//:0") {` is that correct?

**Comment by poteto** [comment]
You're right, it's actually a bug with ember-in-viewport. It should be set before it is triggered. The recommended way is to use `didEnterViewport`, and I'll submit a PR to remove the now redundant check once I have that bugfix in.

Thanks for reporting!

**Comment by fsmanuel** [comment]
Thanks for the great improvements!
