### ISSUE TITLE
Deprecation "A property of... was modified inside the didInsertElement hook." after upgrading to ember 1.13

### ISSUE THREAD

**Issue by mhretab** [twokul/ember-lazy-image#34]
Hi,
I am getting the following deprecation warning from the component after upgrading to ember 1.13 
>A property of... was modified inside the didInsertElement hook. You should never change properties on components, services or models during didInsertElement because it causes significant performance degradation.

**Comment by Alinaki** [comment]
Have same deprecation notice with latest-ember branch

**Comment by fsmanuel** [comment]
:+1:
