### ISSUE TITLE
add alt attribute support

### ISSUE THREAD

**Issue by laantorchaweb** [twokul/ember-lazy-image#38]
I've tried to add alt attributes and it doesn't seem posible, it's something that can be done easily? I could look at the code to make a PR if neccesary.

Thanks!

**Comment by twokul** [comment]
@laantorchaweb it could be done via `attributeBindings`. I would definitely appreciate help :+1:

**Comment by laantorchaweb** [comment]
Done, it's working ok, I added the proper test, documentation and modified the dummy app, thanks!

**Comment by twokul** [comment]
@laantorchaweb do you mind submitting a PR?

**Comment by laantorchaweb** [comment]
Done, thanks for the quick response and for merging the PR. I'm working on a big project with a lot of images and it's a pleasure to have something like this addon. When you have the time can you push the version to npm so my team can update this to the latest version? Thanks again!

**Comment by twokul** [comment]
published as `0.0.14`
